<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="USHYDAMALBARI1" name="loginTest.LoginTest" tests="6" failures="1" timestamp="03 Oct 2020 13:52:43 GMT" time="74.411" errors="0">
  <testcase name="logout" time="6.426" classname="loginTest.LoginTest"/>
  <testcase name="login1" time="19.152" classname="loginTest.LoginTest"/>
  <testcase name="logout" time="0.000" classname="loginTest.LoginTest">
    <skipped/>
  </testcase> <!-- logout -->
  <testcase name="login1" time="20.846" classname="loginTest.LoginTest">
    <failure type="java.lang.AssertionError" message="Incorrect Username and Password wirh username as Amit and password as aaa">
      <![CDATA[java.lang.AssertionError: Incorrect Username and Password wirh username as Amit and password as aaa
at org.testng.Assert.fail(Assert.java:96)
at loginTest.LoginTest.login1(LoginTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- login1 -->
  <testcase name="logout" time="7.323" classname="loginTest.LoginTest"/>
  <testcase name="login1" time="20.664" classname="loginTest.LoginTest"/>
</testsuite> <!-- loginTest.LoginTest -->
